# netlify.toml

# Build configuration
[build]
  command = "npm run build"
  publish = "dist" 

  [build.environment]
    NODE_VERSION = "20"

# Functions configuration
[functions]
  directory = "netlify/functions"
