# netlify.toml

# Sekcja konfiguracji kompilacji dla Astro
[build]
  # Komenda budowania projektu Astro
  command = "npm run build"
  # Katalog wynikowy po kompilacji
  publish = "dist" 

# Sekcja konfiguracji dla Netlify Functions
[functions]
  # Katalog, w którym Netlify szuka Serverless Functions (nasza funkcja Gemini)
  directory = "netlify/functions"
  # Wymuśmy użycie Node.js w wersji 20 (wymagane przez Gemini API)
  node_version = "20"